feat: Unable to pair to device a second time without reset #104
NebraLtd/hm-config pull request #174
Opened 2022-03-04 10:57 UTC by pritamghanghas

* remove time.sleep for wait
* use threading.Event and threading.Timer to achieve the same

**Long wait between bluetooth advertisement**

- Link: https://github.com/NebraLtd/hm-config/issues/104
- Summary:

**How**
Instead of waiting with time.sleep() in advertisement thread, we use proper thread synchronization primitive threading.Event.

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [x] Thought about variable and method names

2022-03-04 15:11 UTC, posterzh commented
Nicely improved the stopping BLE advertisement by using `should_advertise_bluetooth_condition_event` instead of `sleep`.

2022-03-04 15:12 UTC, posterzh commented
Nicely improved the stopping BLE advertisement by using `should_advertise_bluetooth_condition_event` instead of `sleep`.

2022-03-04 15:12 UTC, posterzh approved these changes

2022-03-04 16:15 UTC, marvinmarnold commented on gatewayconfig/bluetooth/characteristics/wifi_connect_characteristic.py
> +            self, constants.WIFI_CONNECT_CHARACTERISTIC_UUID,
Ideally these auto-lints should go into a separate commit. I also asked @kashifpk not to even do autolinting like this a while ago. My thinking is that unless a linting rule is codified in our workflow [linter](https://github.com/NebraLtd/hm-config/blob/master/.github/linters/.flake8), it is an opinion relative to your environment and not an absolute truth.

@NebraLtd/developers I suggest you make sure your auto linting is consistent with our workflow linting, and/or update the workflow linter too.

2022-03-07 19:48 UTC, marvinmarnold requested changes

2022-03-07 19:48 UTC, marvinmarnold commented on gatewayconfig/gatewayconfig_app.py
> +            self.user_button = Button(
And this linting is just wrong. We have a [120char limit](https://github.com/NebraLtd/hm-config/blob/bee8b9146f109cf6d45a76de3e3ce86d365f16c0/.github/linters/.flake8#L2).

2022-03-07 20:22 UTC, marvinmarnold commented on gatewayconfig/processors/bluetooth_advertisement_processor.py
>                  self.shared_state.should_scan_wifi = True
Doesn't have anything to do with your changes, but this is confusing. I didn't realize/forgot this class is also responsible for setting the wifi scan flag. Can you create a new issue to address this weirdness. That ticket should include:

- Comments added to this class to clarify. Possibly changing the class name too.
- Triggering advertisement from some of the wifi related characteristics

2022-03-08 15:34 UTC, pritamghanghas commented
Done with changes.

2022-03-08 17:26 UTC, pritamghanghas commented
Fixed all comments and remove unnecessary linting as well.

2022-03-08 20:43 UTC, marvinmarnold approved these changes

2022-03-08 20:43 UTC, marvinmarnold commented on gatewayconfig/processors/bluetooth_advertisement_processor.py
> +            logger.debug("cancelling existing stop advertisement timer")
Inconsistent capitalization in logging messages in this PR.

2022-03-09 07:35 UTC, merged